Styled Counter component
isdi-coders-202207-bcn-coding-adventure/aron-ilie-front pull request #3
Opened 2022-08-22 14:44 UTC by aronilie

2022-08-22 14:48 UTC, luisdudamel requested changes

2022-08-22 14:48 UTC, luisdudamel commented on src/components/Counter/Counter.tsx
> +        <span className="counter-letter">days</span>
Hola Aron.
En BEM, el guión es para modificadores, no para elementos.

2022-08-22 14:48 UTC, luisdudamel commented on src/components/Counter/CounterStyled.tsx
> +  .counter-number {
Hola Aron,
En styled components, aprovechemos el nesteo de selectores.
No repetimos varias veces un mismo selector que comienza igual.

2022-08-23 11:04 UTC, mariogl commented on src/components/Counter/Counter.tsx
> +        <span className="counter-letter">days</span>
Ojo que un solo guión no es nada en BEM.

2022-08-23 11:06 UTC, aronilie commented
Si, era para no ponerlo en camel case


El mar, 23 ago 2022 a las 13:04, mariogl ***@***.***>)
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/components/Counter/Counter.tsx
> <https://github.com/isdi-coders-202207-bcn-coding-adventure/aron-ilie-front/pull/3#discussion_r952468500>
> :
>
> >  const Counter = (): JSX.Element => {
>
>    return (
>
> -    <ul>
>
> -      <li>
>
> -        <span className="counter-number">02</span>
>
> -        <span>days</span>
>
> +    <CounterStyled>
>
> +      <li className="unit-counter-container">
>
> +        <div className="counter-number-container">
>
> +          <span className="counter-number">02</span>
>
> +        </div>
>
> +        <span className="counter-letter">days</span>
>
>
> Ojo que un solo guión no es nada en BEM.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/isdi-coders-202207-bcn-coding-adventure/aron-ilie-front/pull/3#discussion_r952468500>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZH2DF4HEFEN5VQFOYADJIDV2SV5VANCNFSM57H63EKQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <isdi-coders-202207-bcn-coding-adventure/aron-ilie-front/pull/3/review/1081921326
> @github.com>
>

2022-08-23 11:13 UTC, luisdudamel approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-23 11:14 UTC, merged

2022-08-24 18:26 UTC, mariogl commented
@aronilie el contador tiene que estar centrado tanto en la vertical como en la horizontal del viewport, y el h1 en blanco.

2022-08-25 10:11 UTC, mariogl commented
> @aronilie el contador tiene que estar centrado tanto en la vertical como en la horizontal del viewport, y el h1 en blanco.

@aronilie